plugins {
    id 'dev.architectury.loom'
}

architectury {
    platformSetupLoomIde()
    fabric()
}

dependencies {
    minecraft "com.mojang:minecraft:${rootProject.minecraft_version}"
    mappings loom.officialMojangMappings()

    modImplementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"

    // Local JARs (ForgeConfigAPIPort, geckolib, architectury-api, commons, …)
    implementation fileTree(dir: rootProject.file('libs'), include: ['*.jar'])

    // The common module (cross-platform code)
    implementation project(path: ":common", configuration: "namedElements")
}
