pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        maven { url 'https://maven.architectury.dev/' }
        maven { url 'https://maven.terraformersmc.com/' }
        maven { url 'https://maven.fabricmc.net/' }
    }
}
rootProject.name = 'Litte-maid'
include 'common', 'fabric'
