plugins {
    id 'architectury-plugin'
    id 'dev.architectury.loom'
}

architectury {
    common(rootProject.enabled_platforms.split(","))
}

dependencies {
    modImplementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"
    
    minecraft "com.mojang:minecraft:1.21.11"
    mappings loom.officialMojangMappings()
    
    modImplementation "dev.architectury:architectury:${rootProject.architectury_version}"
    compileOnly "dev.architectury:architectury-injectables:1.0.13"
}
