name: Build YSM Mod

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload Fabric Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: YSM-Fabric
          path: fabric/build/libs/*.jar
          
      - name: Upload Common Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: YSM-Common
          path: common/build/libs/*.jar
